### ISSUE TITLE
See if it's possible to add a popup-preview from Tagging Dialog

### ISSUE THREAD

**Issue by LowellMontgomery** [mcrosson/lr_plugin_computer_vision_tagging#10]
One thing I've been wondering about (if it's possible to do at all) is whether it could be that clicking on a thumbnail in a tagging dialog could bring up a full-screen (or at least larger) preview of the image. Currently, there is no way to confirm whether some tags are accurate or not, e.g. from a thumbnail, it can be difficult to be sure whether a "no person" tag is accurate, so then I need to remember to cull inaccurate tags (or manually add some of the suggested tags that I'd thought weren't appropriate till I took another close look). Even linking to a 1-2MP image sent to the tagging service would provide a lot more detail than can be seen in the thumbnails.

**Comment by mcrosson** [comment]
>One thing I've been wondering about (if it's possible to do at all) is whether it could be that clicking on a thumbnail in a tagging dialog could bring up a full-screen (or at least larger) preview of the image. Currently, there is no way to confirm whether some tags are accurate or not, e.g. from a thumbnail, it can be difficult to be sure whether a "no person" tag is accurate, so then I need to remember to cull inaccurate tags (or manually add some of the suggested tags that I'd thought weren't appropriate till I took another close look). Even linking to a 1-2MP image sent to the tagging service would provide a lot more detail than can be seen in the thumbnails.
I don't believe you can stack dialog windows in Lightroom. I'll keep this open and see if it is an option going forward. I'm currently in the middle of adding another set of APIs from Microsoft (Phase 12 in project plan) and will loop around to look at this closer once I'm past my work on Phase 12 is complete.

**Comment by mcrosson** [comment]
Would the included screenshot be something similar to what you're looking for? I think I figured out a proper way to get this to work. It will involve nested dialogs but I think that should be OK all considered.

Note this screenshot is just me trying to get the fundamentals of nested dialogs working, I need to do a bit more work to get it to show the full image correctly and allow scrolling, etc.

![nested dialogs](https://cloud.githubusercontent.com/assets/2058383/20611458/ade5ae00-b278-11e6-9866-276d28a1b32c.jpg)

**Comment by mcrosson** [comment]
Further update: when the 2nd window is open you can't interact with the first, will that pose a problem?

**Comment by mcrosson** [comment]
This is what I have so far. You can't interact with the tagging dialog while the "full size" preview is open. However, you will be able to at least pop open a larger view of the image from within the tagging dialog.

I also can't easily add zoom/scroll features at this point to the dialog. I'm thinking a simple width/height preference would be sufficient.

Thoughts? I should be able to get this added in pretty short order if the above items are OK for your needs.

![preview full size image](https://cloud.githubusercontent.com/assets/2058383/20611565/1eff62aa-b27b-11e6-832c-689557ce46e0.jpg)

**Comment by mcrosson** [comment]
Given you sent another message shortly after my previous update I went ahead and added the functionality. It may not be perfect but given the limitations of multiple open dialog windows, I think the solution is "good enough".

**Comment by LowellMontgomery** [comment]
I hadn't seen you were working on this already. This is awesome and exactly what I was hoping we could implement... just a way to get back to a close look at the image in question to verify that tags are (or are not) appropriate. Very cool. 😄 👍
