### ISSUE TITLE
Add better debug support

### ISSUE THREAD

**Issue by mcrosson** [mcrosson/lr_plugin_computer_vision_tagging#12]
Reported originally in #8 by @LowellMontgomery 

By the way (somewhat relevant to this ticket), maybe we could add http://www.johnrellis.com/lightroom/debugging-toolkit.htm implementation to this project? If you change the plugin extension name to lrplugin, it ignores the debug stuff entirely, so it's nice for having a way to just output stuff in a clean way. And it's error debugging window is truly gold... If your code gets broken, it's much nicer than what you see without it...

I used it when I was sorting out some issues in my https://github.com/LowellMontgomery/LrIptcCodeHelper, so you can see examples of it in use. The way I've got it configured, my "Git Checkouts" directory is where both the module and my plugin's project directory are located, but the .lrdevplugin directory is an extra directory deeper (as in your project), since the documentation is not inside the actual plugin. So configuration looks like:

```lua
local Require = require 'Require'.path ("../../debugscript.lrdevplugin")
local Debug = require 'Debug'.init ()
require 'strict'
```

:point_up: That is added to any file that needs debugging and a copy of his Require.lua needs to be added to the project.

**Comment by LowellMontgomery** [comment]
Note: I forgot to mention that function calls also need to be wrapped in Debug.showErrors()... then, whenever any errors arise, you get an awesome debugging system automatically called up. Of course you should read the documentation to properly implement it, but I've found it very helpful.

**Comment by mcrosson** [comment]
Added per instructions on referenced website

**Comment by LowellMontgomery** [comment]
You only added the files. It doesn't look like it's been implemented at all.

1. At least some of the files should have some new lines at the top linking to it so it can be used.
e.g.:

> local Require = require 'Require'.path ("../../debugscript.lrdevplugin")
> local Debug = require 'Debug'.init ()
> require 'strict'

Note: This example would not work with the location you have the debugger installed, of course (there, it would be just `../debugscript.lrdevplugin`), but personally, I'd put it a level up and insert directions for anyone helping develop this project to download and install it at the same level as their Git checkout. The "require" for the debugger is ignored by the Require script you DO include, if running from an .lrplugin context (not .lrdevplugin). By installing it a level up, it's handily available to other Lightroom plugin projects you might begin without needing to have multiple copies of it floating around or including it in your actual project (except for the requisite Require.lua).

Anyway, IMHO, that full module really shouldn't be included in your Github project.... Really, I would move it outside the project or at least .gitignore it (and include directions for contributors to download and add this module in Lightroom, the latter of which they would need to do, anyway).

2. You need to wrap certain functions in the Debug.showErrors() for full power to be revealed. See the full directions for configuration/installation. (Debugging Toolkit.htm, in that directory I would install in Lightroom as a plugin/module, but not include in this project).

Anyway, I was a bit surprised to see that this ticket was closed as completed when the functionality is not at all implemented. Then again, I guess it _was_ Thanksgiving and you probably had other things on your mind. 😉  (Really, kudos for all you DID get done on a day most people aren't doing anything like that... I was amazed to see you'd already implemented my other suggestions and that they were actually working pretty well).

**Comment by LowellMontgomery** [comment]
@mcrosson Note that the website where you download the plugin does NOT include the full config directions, which are included in the .htm file within the module. It looks similar, but the downloaded HTM file has a lot more information and includes the full installation/implementation directions.

I'd like to be able to call Debug.lognpp() on some bits of code, so I'll probably at least add the "require lines" to some of the Lua files. I'll reference the copy that I have stored outside this project. If you really do feel it's appropriate to include this in your Github repo, we can change the path.

**Comment by LowellMontgomery** [comment]
@mcrosson Or maybe you just have some uncommitted work that didn't get in? (When I pulled on your master, I did get the new files, just none of the changes to your lua files which would be expected for actual implementation of the toolkit.

(If that's all this was, I'll feel silly for having written all I did in my last two comments, but at least you will notice... hopefully before you've pruned a branch and lost that work)

**Comment by LowellMontgomery** [comment]
This issue should be re-opened, IMHO. Even putting just the "require" lines into any file (even the KwUtils) caused the "yield error" and meant the tagging dialog never appeared. Only the Plugin Manager showed the issue:

```
**** Error 1
An error occurred while attempting to run one of the plug-in’s scripts.
attempt to yield across metamethod/C-call boundary

**** Error 2
Could not load the post-processing filter from this plug-in.
attempt to yield across metamethod/C-call boundary
```

We should get to the bottom of that, if possible, and try to make use of this great tool. I've found it very useful in my other projects.

**Comment by LowellMontgomery** [comment]
https://forums.adobe.com/message/9177930#9177930 I've put it out there and John Ellis has responded with something we might want to look for... methods which should be called from within an `LrTasks.startAsyncTask` block... there may be something like that here somewhere.

**Comment by LowellMontgomery** [comment]
@mcrosson Please re-open this issue. I'm trying to resolve the problems on a debugging branch that should be connected with this ticket.

My local branch (published to my Github fork) is:
2016-12-03-debug-yield-issue

Unfortunately, now things seem more broken and I/we need to figure it out, if we can. In theory we are calling on functions that should only be called from an LrTasks-started thread (among other similar things), so I've been wrapping code blocks in such calls.

Now I'm getting a new error:
> LrFunctionContext:addCleanupHandler: context has already completed; can not add new handlers

And I'm getting that now, even if the lines related to the Debugging Toolkit are commented out. Ideally, I'd like to get this branch sorted and into master ASAP, since any other branch we do significant work on will likely be in conflict with it (due to indentation changes in the affected code blocks). I just had to resolve a merge conflict I'd made, myself, since I didn't yet have my other "tweaks" branch in my local master when I started debugging this issue (and created my new branch for it).

**Comment by mcrosson** [comment]
Re-opened for tracking per @LowellMontgomery request

@LowellMontgomery I'm going to defer to you on this one for the time being. I'll try to jump in at some point but I'm not sure what my schedule holds over the next few weeks yet.
