### ISSUE TITLE
Bug: Unable to Export - LrRecursionGuard error

### ISSUE THREAD

**Issue by LowellMontgomery** [mcrosson/lr_plugin_computer_vision_tagging#7]
@mcrosson Hi Mike, hope all's well there with you.

Sorry, I haven't had time to work on this in the past while, although I did make a start on the improvements I'd suggested. Then I ran into this issue and decided, at the time, that I'd need to see if it was replicable on the master branch (since I'd had some merge conflicts to resolve when merging master into my feature branch). But my dad was visiting (from your neck of the woods—he flew out of DTW last weekend) and I never had time to get back to LR stuff. Anyway, I was able to replicate the issue in "master" and am now wondering whether the plugin is generally broken (affecting everyone), broken just for Mac users, or perhaps only an issue when using certain settings. I'm guessing/hoping it's a general issue and you've just not had time to use the plugin, yourself, since the last changes you made and so didn't notice it broke things? It seems to be related to the changes in your use of LrRecursionGuard. I would try to fix that, but I'm not sure what that's for, actually. (BTW, some of the utility functions I've written for dealing with a hierarchical keyword vocabulary DO require recursive logic, so I hope that the need to use that is not going to cause issues for those functions—I'm assuming not, but just wanted to say that we cannot prevent recursive function calls entirely if we want to implement what I'm doing.)

When I attempt to export, I see an error dialog that says:
> Unable to Export:
> An internal error has occurred: LrRecursionGuard:performWithGuard(): must be called with a function as first argument.

Obviously this blocks me getting to the tagging dialog, where the work I'm doing would be visible, so this bug is currently a "blocker issue" for that feature.

**Comment by mcrosson** [comment]
@LowellMontgomery have you tried running the plugin more than once? I received the error the other day and running the plugin twice cleared it up for me. 

I do have a note to look into this further and I think it's related to the tokens expiring and the way I'm using the recursion guard. I'm pretty sure I know the fix but I need to find some time to sit down and get it done.

**Comment by LowellMontgomery** [comment]
@mcrosson Good call. 👍  

That does seem to further describe the issue. Re-running it now, opened the tagging dialog. I'm now in the middle of some improvements to another LR plugin, so this isn't the ideal time to break from that, but this means that this issue is no longer a "blocker" for me (although it is an important bug prioritize getting fixed, I can obviously attempt to export again whenever I run into this issue). It happened the other day in my feature branch and then it was several days before I attempted it in the master branch, so in that time, the token would have expired.

**Comment by mcrosson** [comment]
This should be fixed now. Changes on master branch.

**Comment by LowellMontgomery** [comment]
@mcrosson Good. I'll merge master (again) on my feature branch. I hope to have some time to get it sorted by the weekend. I've been working on my libraries of helper functions and some other refactoring for those and for other plugins, but should have some time (later this week) to get that all implemented, hopefully before changes you've made are in conflict... ;-)
