### ISSUE TITLE
Bring back the "other keywords" list

### ISSUE THREAD

**Issue by LowellMontgomery** [mcrosson/lr_plugin_computer_vision_tagging#9]
I think that the way the safx plugin works, by showing the other keywords for the photo (already added, but not from the tagging AI) is helpful. It makes it clear whether we have synonymous keywords already assigned (which may need some tweaks to be better in line with the terms that the AI suggests) and maybe helps clarify whether some suggested terms are appropriate (when one can only see a thumbnail-sized version, since the tagging window does not allow for going back to the library to "take a closer look").

Anyway, I do think it's helpful to have such a list below the columns of checkboxes that correspond to the AI-suggested tags.

**Comment by mcrosson** [comment]
I've never actually seen the SAFX output. The plugin never worked for me. i can certainly add a list of keywords that were already added to the photo as another block in the dialog. My first thought is just a static list of keywords as a list (no checkboxes) below the tags returned by an API. Would that work for what you need/want?

**Comment by mcrosson** [comment]
Implemented as an extra group at the bottom of the tagging dialog column.

**Comment by LowellMontgomery** [comment]
That's exactly what I had in mind, yes (though I haven't actually seen the output yet). It should ideally be all the keywords in use for a photo which were NOT returned by the service (those returned by the service will be shown with an asterisk). I do think that allowing changes to those keywords would be handy, but it would require more processing of the form and the simple list of keywords can be rendered from the pre-formatted list of terms (without requesting keyword objects and calling getName() on each.

**Comment by mcrosson** [comment]
I'm going to add the 2nd part (show only non-AI tags / allow editing) to the project plan. I need to think about how I'd put the editing together and I also want to hold off making any updates to the existing tags section of the dialog until after the hierarchical tag changes are merged. You have some great utilities I'd like to leverage when making the updates.
